### ISSUE TITLE
include error in Android.

### ISSUE THREAD

**Issue by XiaoLinSoft** [Senspark/ee-x#20]
I am trying to add the EE-X library to my Android game.
//-----------------------------------------------------------------
Getting started
Android
Clone the repository.

Let CLONE_PATH be where you cloned the repository to.

Modify Android.mk:
$(call import-add-path, CLONE_PATH)
$(call import-module, ee-x/jni)

Modify main.cpp:
#include <jni.h>
#include <ee/Core.hpp>

void cocos_android_app_init(JNIEnv* env) {
    ...
    JavaVm* vm;
    env->GetJavaVm(&vm);
    ee::JniUtils::setVm(vm);
}
//----------------------------------------------------------------

But I have got the error in main.cpp
#include <ee/Core.hpp>
I can't include Core.hpp

![main](https://user-images.githubusercontent.com/27324067/43707251-316ca30a-999a-11e8-9f12-d1308fd7af91.png)

Please let me know how to resolve this issue.

**Comment by enrevol** [comment]
Please show me your Android.mk

**Comment by XiaoLinSoft** [comment]
LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

$(call import-add-path,$(LOCAL_PATH)/../../../cocos2d)
$(call import-add-path,$(LOCAL_PATH)/../../../cocos2d/external)
$(call import-add-path,$(LOCAL_PATH)/../../../cocos2d/cocos)
$(call import-add-path,$(LOCAL_PATH)/../../../cocos2d/cocos/audio/include)

LOCAL_MODULE := MyGame_shared

LOCAL_MODULE_FILENAME := libMyGame

LOCAL_SRC_FILES := $(LOCAL_PATH)/hellocpp/main.cpp \
$(LOCAL_PATH)/../../../Classes/AppDelegate.cpp \
$(LOCAL_PATH)/../../../Classes/HelloWorldScene.cpp \
$(LOCAL_PATH)/../../../Classes/GameScene.cpp \
$(LOCAL_PATH)/../../../Classes/numberSprite.cpp \
$(LOCAL_PATH)/../../../Classes/sudokuentity.cpp \
$(LOCAL_PATH)/../../../Classes/CCCalendar.cpp \
$(LOCAL_PATH)/../../../Classes/CCCalendarDayCell.cpp \
$(LOCAL_PATH)/../../../Classes/CCCalendarLayer.cpp \
$(LOCAL_PATH)/../../../Classes/ChangeThemeLayer.cpp \
$(LOCAL_PATH)/../../../Classes/CompleteScene.cpp \
$(LOCAL_PATH)/../../../Classes/DailyChallengesLayer.cpp \
$(LOCAL_PATH)/../../../Classes/DifficultLayer.cpp \
$(LOCAL_PATH)/../../../Classes/FeedbackLayer.cpp \
$(LOCAL_PATH)/../../../Classes/GameOverLayer.cpp \
$(LOCAL_PATH)/../../../Classes/RateLayer.cpp \
$(LOCAL_PATH)/../../../Classes/CustomMenuItemButton.cpp \
$(LOCAL_PATH)/../../../Classes/ChangeDiffLayer.cpp

LOCAL_CPPFLAGS := -DSDKBOX_ENABLED \
-DSDKBOX_COCOS_CREATOR
LOCAL_LDLIBS := -landroid \
-llog
LOCAL_C_INCLUDES := $(LOCAL_PATH)/../../../Classes

# _COCOS_HEADER_ANDROID_BEGIN
# _COCOS_HEADER_ANDROID_END

LOCAL_WHOLE_STATIC_LIBRARIES += PluginShare
LOCAL_WHOLE_STATIC_LIBRARIES += sdkbox
LOCAL_STATIC_LIBRARIES += ee_x_ironsource_static

LOCAL_STATIC_LIBRARIES := cocos2dx_static

# _COCOS_LIB_ANDROID_BEGIN
# _COCOS_LIB_ANDROID_END

include $(BUILD_SHARED_LIBRARY)

$(call import-add-path, $(LOCAL_PATH)/../../../cocos2d)
$(call import-add-path,$(LOCAL_PATH))
$(call import-module, cocos)
$(call import-module, ./sdkbox)
$(call import-module, ./pluginshare)

$(call import-add-path,/Users/macintoshi/Documents/Work/Sudoku/Sudoku-Android-2/Sudoku/proj.android)
$(call import-module, ee-x/jni)

# _COCOS_LIB_IMPORT_ANDROID_BEGIN
# _COCOS_LIB_IMPORT_ANDROID_END

**Comment by XiaoLinSoft** [comment]
This is my Android.mk.

**Comment by enrevol** [comment]
```
LOCAL_STATIC_LIBRARIES += ee_x_ironsource_static
LOCAL_STATIC_LIBRARIES := cocos2dx_static
```

Should be

```
LOCAL_STATIC_LIBRARIES := cocos2dx_static
LOCAL_STATIC_LIBRARIES += ee_x_ironsource_static
```

**Comment by enrevol** [comment]
You are overwriting `LOCAL_STATIC_LIBRARIES` by using `:=` so `LOCAL_STATIC_LIBRARIES += ee_x_ironsource_static` has no effect.

**Comment by XiaoLinSoft** [comment]
Thank you.

But I am getting the error still. 

![main1](https://user-images.githubusercontent.com/27324067/43708298-bb2a7e1c-999c-11e8-8bc7-bb2e2c8cd248.png)

**Comment by XiaoLinSoft** [comment]
//--------------------------------------------------------
Getting started
...
...
Add or modify MyApplication.java:
import com.ee.core.PluginManager;

public MyApplication extends Application {
    @Override
    public void onCreate() {
        PluginManager.getInstance().initializePlugins(this);
    }
}

//-------------------------------------------------------

And I have a question.
Should I create "MyApplication.java"?

**Comment by enrevol** [comment]
Yes

**Comment by XiaoLinSoft** [comment]
Thank you.
