### ISSUE TITLE
getIronSource() Error in Android

### ISSUE THREAD

**Issue by XiaoLinSoft** [Senspark/ee-x#22]
I am trying to add the IronSource in Android app.
Building app is success.
But the android app crashes when I call testIronSourceRewardedVideo().

void testIronSourceRewardedVideo() {
    auto rewardedVideo =
            ee::runOnUiThreadAndWaitResult<std::shared_ptr<ee::IRewardedVideo>>([] {
                sudoku::FunctionLogger logger("Create ironSource rewarded video");
                return getIronSource()->createRewardedVideo(getIronSourceRewardedVideoId());
            });

    float delay = 0.0f;
    sudoku::scheduleOnce(delay += 1.0f, [rewardedVideo] {
        ee::runOnUiThread([rewardedVideo] {
            sudoku::FunctionLogger logger("Show ironSource rewarded video");
            rewardedVideo->show();
        });
    });

    rewardedVideo->setResultCallback([](bool success){
    });
}

The following error has occurred:

//-------------------------------------------------    

08-06 21:09:22.116 23033-23123/com.handpatton.sudoku E/com.ee.core.MessageBridge: call: Utils_isMainThread doesn't exist!

    --------- beginning of crash
08-06 21:09:22.117 23033-23123/com.handpatton.sudoku A/libc: /Users/macintoshi/Documents/Work/Sudoku/Sudoku-Android-2/Sudoku/proj.android/ee-x/jni/../src/ee/core/Utils.cpp:70: bool ee::core::toBool(const std::string &): assertion "value == "true" || value == "false"" failed
08-06 21:09:41.519 23033-23123/com.handpatton.sudoku A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 23123 (GLThread 249)

//-------------------------------------------------    

Please let me know how to fix this error.

**Comment by enrevol** [comment]
Make sure that your application is registered in AndroidManifest.xml
https://stackoverflow.com/questions/2929562/register-application-class-in-manifest

**Comment by XiaoLinSoft** [comment]
This is my AndroidManifest.xml.

//-----------------------------------------

<?xml version='1.0' encoding='UTF-8'?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.handpatton.sudoku" android:installLocation="auto">
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-feature android:glEsVersion="0x00020000" />
    <application android:allowBackup="true" android:icon="@mipmap/ic_launcher" android:label="@string/app_name">
        <meta-data android:name="android.app.lib_name" android:value="MyGame" />
        <activity android:configChanges="orientation|keyboardHidden|screenSize" android:label="@string/app_name" android:name="org.cocos2dx.cpp.AppActivity" android:screenOrientation="portrait" android:theme="@android:style/Theme.NoTitleBar.Fullscreen">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
        <activity android:configChanges="orientation|screenSize" android:excludeFromRecents="true" android:exported="false" android:name="com.twitter.sdk.android.core.identity.OAuthActivity" />
        <service android:enabled="true" android:exported="false" android:name="com.twitter.sdk.android.tweetcomposer.TweetUploadService" />
    </application>
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.SEND_SMS" />
</manifest>

//-----------------------------------------

**Comment by enrevol** [comment]
You need to add `android:name=".MyApplication"` in `application` tag (`MyApplication` should be your application class name) like this:
```
<application
    android:name=".MyApplication"
    android:allowBackup="true"
    android:icon="@mipmap/ic_launcher"
    android:label="@string/app_name">
```

**Comment by enrevol** [comment]
Try adding `implementation 'com.android.support:support-v4:27.1.1'` in your `build.gradle` like this:
```
dependencies {
    implementation 'com.android.support:support-v4:27.1.1'
}
```

**Comment by XiaoLinSoft** [comment]
OK, It's working well now.
Thank you very much.

**Comment by XiaoLinSoft** [comment]
And I am trying to implement other AD module.
Could you please add another AD(mopub and kochava) to this ee-x library?

**Comment by enrevol** [comment]
Currently we only implement what we use, so we won't add other ads until we need it.

**Comment by XiaoLinSoft** [comment]
OK, Thank you.
