### ISSUE TITLE
IronSource Error

### ISSUE THREAD

**Issue by XiaoLinSoft** [Senspark/ee-x#7]
I got this error in implementing IronSource Video AD.

API: showRV with placement name DefaultRewardedVideo
Assertion failed: (successful), function show, file /Users/macintoshi/Documents/Work/Sudoku/Sudoku/proj.ios_mac/Pods/ee-x/src/ee/ironsource/internal/IronSourceRewardedVideo.cpp, line 52.

Please help me.

**Comment by enrevol** [comment]
Do you use only ironSource?

**Comment by XiaoLinSoft** [comment]
Yes, I use only ironsource.

**Comment by enrevol** [comment]
Make sure that you don't call show() twice at a time.
The first show() should finish (via setResultCallback) before the second show().

**Comment by XiaoLinSoft** [comment]
OK, I will try it.
And how can I know the callback when the video ad finished?

**Comment by enrevol** [comment]
Here you are:
```
auto videoAd = ironSource->createRewardedVideo("your_placement_id");
videoAd->setResultCallback([](bool success) {
    // ...
});
```

**Comment by XiaoLinSoft** [comment]
OK, Thank you.
